# Generated by Django 4.0.5 on 2022-06-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.TextField(max_length=100)),
                ('activoCategoria', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDonante', models.TextField()),
                ('apellidoDonante', models.TextField()),
                ('montoDonacion', models.TextField()),
                ('medioDePago', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.TextField(max_length=100)),
                ('activoMarca', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='medioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedio', models.TextField()),
                ('activoMedio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.TextField()),
                ('precioProducto', models.TextField()),
                ('precioCosto', models.TextField()),
                ('stockProducto', models.TextField()),
                ('descripcionProducto', models.TextField(max_length=100)),
                ('categoriaProducto', models.TextField()),
                ('marcaProducto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runSus', models.TextField(max_length=10)),
                ('dvSus', models.TextField(max_length=1)),
                ('nombreSus', models.TextField(max_length=20)),
                ('apellidoSus', models.TextField(max_length=20)),
                ('emailSus', models.TextField(max_length=30)),
                ('celularSus', models.TextField(max_length=11)),
                ('tipoDeUsuario', models.TextField()),
                ('activoSus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoUsuario', models.TextField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.TextField(max_length=10)),
                ('dv', models.TextField(max_length=1)),
                ('nombreUsuario', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=30)),
                ('password', models.TextField()),
                ('tipoDeUsuario', models.TextField()),
            ],
        ),
    ]
