# Generated by Django 4.0.5 on 2022-06-23 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marcaProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioCosto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockProducto',
            field=models.IntegerField(),
        ),
    ]
