# Generated by Django 4.0.5 on 2022-06-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_producto_categoriaproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.TextField(max_length=600),
        ),
    ]
